print(len("adsdas"))
print("test STRING".capitalize())
print("text text1 text2".split())
print("Good morning".replace("morning","night"))
print("afdfsASs".upper())
print("asdasADDASFVFDV DFVF".lower())
print("     a".lstrip())
print("asdsa         ".rstrip())
print("      ad fasda   ".strip())